package com.e.livingdex_tracker;

import androidx.appcompat.app.AppCompatActivity;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Switch;
import android.widget.Toast;

public class Gen4Shinies extends AppCompatActivity {

    /*private Switch starly;
    private Switch bidoof;
    private Switch shinx;
    private Switch kricketot;
    private Switch magikarp;
    private Switch wurmple;
    private Switch shellos;
    private Switch tentacool;
    private Switch finneon;
    private Switch shellder;
    private Switch murkrow;
    private Switch misdreavus;
    private Switch buneary;
    private Switch gastly;
    private Switch machop;
    private Switch geodude;
    private Switch stunky;
    private Switch onix;
    private Switch cleffa;
    private Switch meditite;
    private Switch chingling;
    private Switch barboach;
    private Switch hoothoot;
    private Switch snover;
    private Switch dratini;
    private Switch chansey;
    private Switch bonsly;*/
    private Switch mimejr;
    private Switch spiritomb;
    private Switch wooper;
    private Switch remoraid;
    private Switch sharpedo;
    private Switch glameow;
    private Switch clamperl;
    private Switch chinchou;
    private Switch bellsprout;
    private Switch luvdisc;
    private Switch ariados;
    private Switch heatran;
    private Switch exeggcute;
    private Switch kangaskhan;
    private Switch yanma;
    private Switch shroomish;
    private Switch carnivine;
    private Switch burmy;
    private Switch munchlax;
    private Switch pichu;
    private Switch eevee;
    private Switch igglypuff;
    private Switch meowth;
    private Switch plusle;
    private Switch castform;
    private Switch spoink;
    private Switch skitty;
    private Switch natu;


    public static final String SHARED_PREFS = "sharedPrefs";
    /*public static final String STARLY = "starly";
    public static final String BIDOOF = "bidoof";
    public static final String SHINX = "shinx";
    public static final String KRICKETOT = "kricketot";
    public static final String MAGIKARP = "magikarp";
    public static final String WURMPLE = "wurmple";
    public static final String SHELLOS = "shellos";
    public static final String TENTACOOL = "tentacool";
    public static final String FINNEON = "finneon";
    public static final String SHELLDER = "shellder";
    public static final String MURKROW = "murkrow";
    public static final String MISDREAVUS = "misdreavus";
    public static final String BUNEARY = "buneary";
    public static final String GASTLY = "gastly";
    public static final String MACHOP = "machop";
    public static final String GEODUDE = "geodude";
    public static final String STUNKY = "stunky";
    public static final String ONIX = "onix";
    public static final String CLEFFA = "cleffa";
    public static final String MEDITITE = "meditite";
    public static final String CHINGLING = "chingling";
    public static final String BARBOACH = "barboach";
    public static final String HOOTHOOT = "hoothoot";
    public static final String SNOVER = "snover";
    public static final String DRATINI = "dratini";
    public static final String CHANSEY = "chansey";
    public static final String BONSLY = "bonsly";*/
    public static final String MIMEJR = "mimejr";
    public static final String SPIRITOMB = "spiritomb";
    public static final String WOOPER = "wooper";
    public static final String REMORAID = "remoraid";
    public static final String SHARPEDO = "sharpedo";
    public static final String GLAMEOW = "zigzagoon";
    public static final String CLAMPERL = "clamperl";
    public static final String CHINCHOU = "chinchou";
    public static final String BELLSPROUT = "bellsprout";
    public static final String LUVDISC = "luvdisc";
    public static final String ARIADOS = "ariados";
    public static final String HEATRAN = "heatran";
    public static final String EXEGGCUTE = "exeggcute";
    public static final String KANGASKHAN = "kangaskhan";
    public static final String YANMA = "yanma";
    public static final String SHROOMISH = "shroomisj";
    public static final String CARNIVINE = "carnivine";
    public static final String BURMY = "burmey";
    public static final String MUNCHLAX = "munchlax";
    public static final String PICHU = "pichu";
    public static final String EEVEE = "eevee";
    public static final String IGGLYPUFF = "igglypuff";
    public static final String MEOWTH = "meowth";
    public static final String PLUSLE = "plusle";
    public static final String CASTFORM = "castform";
    public static final String SPOINK = "spoink";
    public static final String SKITTY = "skitty";
    public static final String NATU = "natu";

    /*private boolean starlyONOFF;
    private boolean bidoofONOFF;
    private boolean shinxONOFF;
    private boolean kricketotONOFF;
    private boolean magikarpONOFF;
    private boolean wurmpleONOFF;
    private boolean shellosONOFF;
    private boolean tentacoolONOFF;
    private boolean finneonONOFF;
    private boolean shellderONOFF;
    private boolean murkrowONOFF;
    private boolean misdreavusONOFF;
    private boolean bunearyONOFF;
    private boolean gastlyONOFF;
    private boolean machopONOFF;
    private boolean geodudeONOFF;
    private boolean stunkyONOFF;
    private boolean onixONOFF;
    private boolean cleffaONOFF;
    private boolean medititeONOFF;
    private boolean chinglingONOFF;
    private boolean barboachONOFF;
    private boolean hoothootONOFF;
    private boolean snoverONOFF;
    private boolean dratiniONOFF;
    private boolean chanseyONOFF;
    private boolean bonslyONOFF;*/
    private boolean mimejrONOFF;
    private boolean spiritombONOFF;
    private boolean wooperONOFF;
    private boolean remoraidONOFF;
    private boolean sharpedoONOFF;
    private boolean glameowONOFF;
    private boolean clamperlONOFF;
    private boolean chinchouONOFF;
    private boolean bellsproutONOFF;
    private boolean luvdiscONOFF;
    private boolean ariadosONOFF;
    private boolean heatranONOFF;
    private boolean exeggcuteONOFF;
    private boolean kangaskhanONOFF;
    private boolean yanmaONOFF;
    private boolean shroomishONOFF;
    private boolean carnivineONOFF;
    private boolean burmyONOFF;
    private boolean munchlaxONOFF;
    private boolean pichuONOFF;
    private boolean eeveeONOFF;
    private boolean igglypuffONOFF;
    private boolean meowthONOFF;
    private boolean plusleONOFF;
    private boolean castformONOFF;
    private boolean spoinkONOFF;
    private boolean skittyONOFF;
    private boolean natuONOFF;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_gen4_shinies);
        /*starly = findViewById(R.id.starlyShinyToggle);
        bidoof = findViewById(R.id.bidoofShinyToggle);
        shinx = findViewById(R.id.shinxShinyToggle);
        kricketot = findViewById(R.id.kricketotShinyToggle);
        magikarp = findViewById(R.id.magikarpShinyToggle);
        wurmple = findViewById(R.id.wurmpleShinyToggle);
        shellos= findViewById(R.id.shellosShinyToggle);
        tentacool= findViewById(R.id.tentacoolShinyToggle);
        finneon= findViewById(R.id.finneonShinyToggle);
        shellder= findViewById(R.id.shellderShinyToggle);
        murkrow = findViewById(R.id.murkrowShinyToggle);
        misdreavus = findViewById(R.id.misdreavusShinyToggle);
        buneary = findViewById(R.id.bunearyShinyToggle);
        gastly = findViewById(R.id.gastlyShinyToggle);
        machop = findViewById(R.id.machopShinyToggle);
        geodude = findViewById(R.id.geodudeShinyToggle);
        stunky = findViewById(R.id.stunkyShinyToggle);
        onix = findViewById(R.id.onixShinyToggle);
        cleffa = findViewById(R.id.cleffaShinyToggle);
        meditite = findViewById(R.id.medititeShinyToggle);
        chingling = findViewById(R.id.chinglingShinyToggle);
        barboach = findViewById(R.id.barboachShinyToggle);
        hoothoot = findViewById(R.id.hoothootShinyToggle);
        snover = findViewById(R.id.snoverShinyToggle);
        dratini = findViewById(R.id.dratiniShinyToggle);
        chansey = findViewById(R.id.chanseyShinyToggle);
        bonsly = findViewById(R.id.bonslyShinyToggle);*/
        mimejr = findViewById(R.id.mimejrShinyToggle);
        spiritomb = findViewById(R.id.spiritombShinyToggle);
        wooper = findViewById(R.id.wooperShinyToggle);
        remoraid = findViewById(R.id.remoraidShinyToggle);
        sharpedo= findViewById(R.id.sharpedoShinyToggle);
        glameow = findViewById(R.id.glameowShinyToggle);
        clamperl = findViewById(R.id.clamperlShinyToggle);
        chinchou = findViewById(R.id.chinchouShinyToggle);
        bellsprout = findViewById(R.id.bellsproutShinyToggle);
        luvdisc = findViewById(R.id.luvdiscShinyToggle);
        ariados = findViewById(R.id.ariadosShinyToggle);
        heatran = findViewById(R.id.heatranShinyToggle);
        exeggcute = findViewById(R.id.exeggcuteShinyToggle);
        kangaskhan = findViewById(R.id.kangaskhanShinyToggle);
        yanma = findViewById(R.id.yanmaShinyToggle);
        shroomish = findViewById(R.id.shroomishShinyToggle);
        carnivine = findViewById(R.id.carnivineShinyToggle);
        burmy = findViewById(R.id.burmyShinyToggle);
        munchlax = findViewById(R.id.munchlaxShinyToggle);
        pichu = findViewById(R.id.pichuShinyToggle);
        eevee = findViewById(R.id.eeveeShinyToggle);
        igglypuff = findViewById(R.id.igglypuffShinyToggle);
        meowth = findViewById(R.id.meowthShinyToggle);
        plusle = findViewById(R.id.plusleShinyToggle);
        castform = findViewById(R.id.castformShinyToggle);
        spoink = findViewById(R.id.spoinkShinyToggle);
        skitty = findViewById(R.id.skittyShinyToggle);
        natu = findViewById(R.id.natuShinyToggle);
        
        Button save = findViewById(R.id.save);

        save.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                saveData();
            }
        });

        loadData();
        updateViews();

    }

    public void saveData(){
        SharedPreferences sharedPreferences = getSharedPreferences(SHARED_PREFS, MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        /*editor.putBoolean(STARLY, starly.isChecked());
        editor.putBoolean(BIDOOF, bidoof.isChecked());
        editor.putBoolean(SHINX, shinx.isChecked());
        editor.putBoolean(KRICKETOT, kricketot.isChecked());
        editor.putBoolean(MAGIKARP, magikarp.isChecked());
        editor.putBoolean(WURMPLE, wurmple.isChecked());
        editor.putBoolean(SHELLOS, shellos.isChecked());
        editor.putBoolean(TENTACOOL, tentacool.isChecked());
        editor.putBoolean(FINNEON, finneon.isChecked());
        editor.putBoolean(SHELLDER, shellder.isChecked());
        editor.putBoolean(MURKROW, murkrow.isChecked());
        editor.putBoolean(MISDREAVUS, misdreavus.isChecked());
        editor.putBoolean(BUNEARY, buneary.isChecked());
        editor.putBoolean(GASTLY, gastly.isChecked());
        editor.putBoolean(MACHOP, machop.isChecked());
        editor.putBoolean(GEODUDE, geodude.isChecked());
        editor.putBoolean(STUNKY, stunky.isChecked());
        editor.putBoolean(ONIX, onix.isChecked());
        editor.putBoolean(CLEFFA, cleffa.isChecked());
        editor.putBoolean(MEDITITE, meditite.isChecked());
        editor.putBoolean(CHINGLING, chingling.isChecked());
        editor.putBoolean(BARBOACH, barboach.isChecked());
        editor.putBoolean(HOOTHOOT, hoothoot.isChecked());
        editor.putBoolean(SNOVER, snover.isChecked());
        editor.putBoolean(DRATINI, dratini.isChecked());
        editor.putBoolean(CHANSEY, chansey.isChecked());
        editor.putBoolean(BONSLY, bonsly.isChecked());*/
        editor.putBoolean(MIMEJR, mimejr.isChecked());
        editor.putBoolean(SPIRITOMB, spiritomb.isChecked());
        editor.putBoolean(REMORAID, remoraid.isChecked());
        editor.putBoolean(SHARPEDO, sharpedo.isChecked());
        editor.putBoolean(GLAMEOW, glameow.isChecked());
        editor.putBoolean(CLAMPERL, clamperl.isChecked());
        editor.putBoolean(CHINCHOU, chinchou.isChecked());
        editor.putBoolean(BELLSPROUT, bellsprout.isChecked());
        editor.putBoolean(LUVDISC, luvdisc.isChecked());
        editor.putBoolean(ARIADOS, ariados.isChecked());
        editor.putBoolean(HEATRAN, heatran.isChecked());
        editor.putBoolean(EXEGGCUTE, exeggcute.isChecked());
        editor.putBoolean(KANGASKHAN, kangaskhan.isChecked());
        editor.putBoolean(YANMA, yanma.isChecked());
        editor.putBoolean(SHROOMISH, shroomish.isChecked());
        editor.putBoolean(CARNIVINE, carnivine.isChecked());
        editor.putBoolean(BURMY, burmy.isChecked());
        editor.putBoolean(MUNCHLAX, munchlax.isChecked());
        editor.putBoolean(PICHU, pichu.isChecked());
        editor.putBoolean(EEVEE, eevee.isChecked());
        editor.putBoolean(IGGLYPUFF, igglypuff.isChecked());
        editor.putBoolean(MEOWTH, meowth.isChecked());
        editor.putBoolean(PLUSLE, plusle.isChecked());
        editor.putBoolean(CASTFORM, castform.isChecked());
        editor.putBoolean(SPOINK, spoink.isChecked());
        editor.putBoolean(SKITTY, skitty.isChecked());
        editor.putBoolean(NATU, natu.isChecked());

        editor.apply();

        Toast.makeText(this, "Data Saved", Toast.LENGTH_SHORT).show();
    }

    public void loadData(){
        SharedPreferences sharedPreferences = getSharedPreferences(SHARED_PREFS, MODE_PRIVATE);
        /*starlyONOFF = sharedPreferences.getBoolean(STARLY, false);
        bidoofONOFF = sharedPreferences.getBoolean(BIDOOF, false);
        shinxONOFF = sharedPreferences.getBoolean(SHINX, false);
        kricketotONOFF = sharedPreferences.getBoolean(KRICKETOT, false);
        magikarpONOFF = sharedPreferences.getBoolean(MAGIKARP, false);
        wurmpleONOFF = sharedPreferences.getBoolean(WURMPLE, false);
        shellosONOFF = sharedPreferences.getBoolean(SHELLOS, false);
        tentacoolONOFF = sharedPreferences.getBoolean(TENTACOOL, false);
        finneonONOFF = sharedPreferences.getBoolean(FINNEON, false);
        shellderONOFF = sharedPreferences.getBoolean(SHELLDER, false);
        murkrowONOFF = sharedPreferences.getBoolean(MURKROW, false);
        misdreavusONOFF = sharedPreferences.getBoolean(MISDREAVUS, false);
        bunearyONOFF = sharedPreferences.getBoolean(BUNEARY, false);
        gastlyONOFF = sharedPreferences.getBoolean(GASTLY, false);
        machopONOFF = sharedPreferences.getBoolean(MACHOP, false);
        geodudeONOFF = sharedPreferences.getBoolean(GEODUDE, false);
        stunkyONOFF = sharedPreferences.getBoolean(STUNKY, false);
        onixONOFF = sharedPreferences.getBoolean(ONIX, false);
        cleffaONOFF = sharedPreferences.getBoolean(CLEFFA, false);
        medititeONOFF = sharedPreferences.getBoolean(MEDITITE, false);
        chinglingONOFF = sharedPreferences.getBoolean(CHINGLING, false);
        barboachONOFF = sharedPreferences.getBoolean(BARBOACH, false);
        hoothootONOFF= sharedPreferences.getBoolean(HOOTHOOT, false);
        snoverONOFF = sharedPreferences.getBoolean(SNOVER, false);
        dratiniONOFF = sharedPreferences.getBoolean(DRATINI, false);
        chanseyONOFF = sharedPreferences.getBoolean(CHANSEY, false);
        bonslyONOFF = sharedPreferences.getBoolean(BONSLY, false);*/
        mimejrONOFF= sharedPreferences.getBoolean(MIMEJR, false);
        spiritombONOFF = sharedPreferences.getBoolean(SPIRITOMB, false);
        wooperONOFF = sharedPreferences.getBoolean(WOOPER, false);
        remoraidONOFF = sharedPreferences.getBoolean(REMORAID, false);
        sharpedoONOFF = sharedPreferences.getBoolean(SHARPEDO, false);
        glameowONOFF = sharedPreferences.getBoolean(GLAMEOW, false);
        clamperlONOFF = sharedPreferences.getBoolean(CLAMPERL, false);
        chinchouONOFF = sharedPreferences.getBoolean(CHINCHOU, false);
        bellsproutONOFF= sharedPreferences.getBoolean(BELLSPROUT, false);
        luvdiscONOFF= sharedPreferences.getBoolean(LUVDISC, false);
        ariadosONOFF= sharedPreferences.getBoolean(ARIADOS, false);
        heatranONOFF = sharedPreferences.getBoolean(HEATRAN, false);
        exeggcuteONOFF = sharedPreferences.getBoolean(EXEGGCUTE, false);
        kangaskhanONOFF = sharedPreferences.getBoolean(KANGASKHAN, false);
        yanmaONOFF = sharedPreferences.getBoolean(YANMA, false);
        shroomishONOFF = sharedPreferences.getBoolean(SHROOMISH, false);
        carnivineONOFF = sharedPreferences.getBoolean(CARNIVINE, false);
        burmyONOFF = sharedPreferences.getBoolean(BURMY, false);
        munchlaxONOFF = sharedPreferences.getBoolean(MUNCHLAX, false);
        pichuONOFF = sharedPreferences.getBoolean(PICHU, false);
        eeveeONOFF = sharedPreferences.getBoolean(EEVEE, false);
        igglypuffONOFF = sharedPreferences.getBoolean(IGGLYPUFF, false);
        meowthONOFF = sharedPreferences.getBoolean(MEOWTH, false);
        plusleONOFF = sharedPreferences.getBoolean(PLUSLE, false);
        castformONOFF = sharedPreferences.getBoolean(CASTFORM, false);
        spoinkONOFF = sharedPreferences.getBoolean(SPOINK, false);
        skittyONOFF = sharedPreferences.getBoolean(SKITTY, false);
        natuONOFF = sharedPreferences.getBoolean(NATU, false);
    }

    public void updateViews(){
        /*starly.setChecked(starlyONOFF);
        bidoof.setChecked(bidoofONOFF);
        shinx.setChecked(shinxONOFF);
        kricketot.setChecked(kricketotONOFF);
        magikarp.setChecked(magikarpONOFF);
        wurmple.setChecked(wurmpleONOFF);
        shellos.setChecked(shellosONOFF);
        tentacool.setChecked(tentacoolONOFF);
        finneon.setChecked(finneonONOFF);
        shellder.setChecked(shellderONOFF);
        murkrow.setChecked(murkrowONOFF);
        misdreavus.setChecked(misdreavusONOFF);
        buneary.setChecked(bunearyONOFF);
        gastly.setChecked(gastlyONOFF);
        machop.setChecked(machopONOFF);
        geodude.setChecked(geodudeONOFF);
        stunky.setChecked(stunkyONOFF);
        onix.setChecked(onixONOFF);
        cleffa.setChecked(cleffaONOFF);
        meditite.setChecked(medititeONOFF);
        chingling.setChecked(chinglingONOFF);
        barboach.setChecked(barboachONOFF);
        hoothoot.setChecked(hoothootONOFF);
        snover.setChecked(snoverONOFF);
        dratini.setChecked(dratiniONOFF);
        chansey.setChecked(chanseyONOFF);
        bonsly.setChecked(bonslyONOFF);*/
        mimejr.setChecked(mimejrONOFF);
        spiritomb.setChecked(spiritombONOFF);
        wooper.setChecked(wooperONOFF);
        remoraid.setChecked(remoraidONOFF);
        sharpedo.setChecked(sharpedoONOFF);
        glameow.setChecked(glameowONOFF);
        clamperl.setChecked(clamperlONOFF);
        chinchou.setChecked(chinchouONOFF);
        bellsprout.setChecked(bellsproutONOFF);
        luvdisc.setChecked(luvdiscONOFF);
        ariados.setChecked(ariadosONOFF);
        heatran.setChecked(heatranONOFF);
        exeggcute.setChecked(exeggcuteONOFF);
        kangaskhan.setChecked(kangaskhanONOFF);
        yanma.setChecked(yanmaONOFF);
        shroomish.setChecked(shroomishONOFF);
        carnivine.setChecked(carnivineONOFF);
        burmy.setChecked(burmyONOFF);
        munchlax.setChecked(munchlaxONOFF);
        pichu.setChecked(pichuONOFF);
        eevee.setChecked(eeveeONOFF);
        igglypuff.setChecked(igglypuffONOFF);
        meowth.setChecked(meowthONOFF);
        plusle.setChecked(plusleONOFF);
        castform.setChecked(castformONOFF);
        spoink.setChecked(spoinkONOFF);
        skitty.setChecked(skittyONOFF);
        natu.setChecked(natuONOFF);

    }
}
